# Generated by Django 5.0.6 on 2025-10-28 20:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gov_id_file_profile_gov_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drug_license_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.drug_license_upload_path, verbose_name='Drug Selling Licence'),
        ),
    ]
