# Generated by Django 5.0.6 on 2025-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='partner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ttype',
            field=models.CharField(choices=[('BOUGHT', 'Bought'), ('SOLD', 'Sold')], max_length=10),
        ),
    ]
