# Generated by Django 5.0.6 on 2025-10-30 13:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_transaction_partner_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_manufacturer_name_ci'),
        ),
    ]
